version: '3.4'

services:
  futurearbitrage.api:
    image: ${DOCKER_REGISTRY-}futurearbitrageapi
    build:
      context: .
      dockerfile: FutureArbitrage.Api/Dockerfile

  products.database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=FutureArbitrage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./.containers/products-db:/var/lib/postgresql/data
    ports:
      - "54321:5432"
