version: '3.4'

services:
  futurearbitrage-api:
    image: futurearbitrage-api
    container_name: api
    build:
      context: .
      dockerfile: FutureArbitrage.Api/Dockerfile
    ports:
      - "8081:8081"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://futurearbitrage-dashboard:18889"
    networks:
      - otel

  futurearbitrage-dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - "18888:18888"
      - "18889:18889"
    networks:
      - otel
  
  futurearbitrage-db:
    image: postgres:latest
    container_name: Futurearbitrage.Db
    environment: 
      - POSTGRES_DB=FutureArbitrage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports: 
      - 5432:5432       
 
networks:
  otel:
