version: '3.4'

services:
  futurearbitrage.api:
    image: ${DOCKER_REGISTRY-}futurearbitrageapi
    container_name: api
    build:
      context: .
      dockerfile: FutureArbitrage.Api/Dockerfile
    ports:
    - 8081:8081
    environment:
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://dashboard:18889
    networks:
    - otel
 
  futurearbitrage.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    restart: always
    ports:
      - "18888:18888"
    networks:
      - otel

networks:
  otel:
    
